import { useState } from 'react';
import { Dna, Info, CheckCircle2, Loader2, AlertTriangle, HelpCircle, X } from 'lucide-react';
import styles from './BlastCard.module.css';

export default function BlastHeader({ status, queryLength, executionTimeMs, hasTopHit }) {
  const [showTooltip, setShowTooltip] = useState(false);

  const searchTimeSec = executionTimeMs ? (executionTimeMs / 1000).toFixed(1) : '1.5';

  return (
    <div className={styles.headerContainer}>
      <div className={styles.cardHeader}>
        <div className={styles.titleGroup}>
          <h3>
            <Dna size={20} style={{ color: '#38bdf8' }} />
            Sequence Similarity Analysis
            <button
              type="button"
              className={styles.tooltipBtn}
              onClick={() => setShowTooltip(!showTooltip)}
              title="What is BLAST?"
              aria-label="What is BLAST information tooltip"
            >
              <HelpCircle size={16} />
            </button>
          </h3>
          <p className={styles.secSub}>
            NCBI BLASTN alignment against the NCBI Nucleotide (nt) reference database.
          </p>
        </div>

        {/* Status Badge */}
        <div>
          {status === 'loading' && (
            <span className={`${styles.statusBadge} ${styles.statusLoading}`}>
              <Loader2 size={14} className="spin" />
              Running BLAST...
            </span>
          )}
          {status === 'completed' && hasTopHit && (
            <span className={`${styles.statusBadge} ${styles.statusSuccess}`}>
              <CheckCircle2 size={14} />
              ✔ Analysis Complete
            </span>
          )}
          {status === 'completed' && !hasTopHit && (
            <span className={`${styles.statusBadge} ${styles.statusInfo}`}>
              <Info size={14} />
              ℹ No Significant Match
            </span>
          )}
          {(status === 'failed' || status === 'error') && (
            <span className={`${styles.statusBadge} ${styles.statusError}`}>
              <AlertTriangle size={14} />
              ⚠ Analysis Error
            </span>
          )}
        </div>
      </div>

      {/* Tooltip Popover */}
      {showTooltip && (
        <div className={styles.tooltipPopover}>
          <div className={styles.tooltipHeader}>
            <strong><Info size={14} /> What is BLAST?</strong>
            <button type="button" className={styles.closeTooltip} onClick={() => setShowTooltip(false)}>
              <X size={14} />
            </button>
          </div>
          <p>
            BLAST (Basic Local Alignment Search Tool) compares the uploaded DNA sequence against reference nucleotide databases maintained by NCBI to identify biologically similar sequences.
          </p>
          <p className={styles.tooltipFooter}>
            ℹ️ This sequence similarity analysis complements—but does not replace—the AI disease prediction generated by the GenomeAI CNN model.
          </p>
        </div>
      )}

      {/* Header Metadata Strip */}
      <div className={styles.headerMetaStrip}>
        <div className={styles.metaChip}>
          <span>Program:</span> <strong>BLASTN</strong>
        </div>
        <div className={styles.metaChip}>
          <span>Database:</span> <strong>NCBI nt</strong>
        </div>
        <div className={styles.metaChip}>
          <span>Query Length:</span> <strong>{queryLength || 201} bp</strong>
        </div>
        <div className={styles.metaChip}>
          <span>Status:</span> <strong>{status === 'loading' ? 'Running...' : 'Completed'}</strong>
        </div>
        <div className={styles.metaChip}>
          <span>Search Time:</span> <strong>{searchTimeSec} sec</strong>
        </div>
      </div>
    </div>
  );
}
